#!/usr/bin/env bash
#
# Launches a hosted Parrot deployment on Lightsail, end to end, from one command.
#
#   ./deploy/launch.sh --domain example.com --subdomain bi
#   ./deploy/launch.sh --host 203.0.113.10            # an instance that already exists
#
# It checks the tools it needs, creates the instance with Terraform unless --host is given, writes
# the host's addresses into deploy/hosted/.env, waits for cloud-init to finish installing Docker,
# and then hands over to deploy/hosted/deploy.sh, which builds the image, transfers it, starts the
# stack and verifies it.
#
# The same script is what the "Deploy Hosted" workflow runs in GitHub Actions, so a machine without
# these tools can launch a deployment from there instead.

set -euo pipefail

usage() {
  cat <<'EOF'
Usage: launch.sh [options]

Provisioning (skipped when --host is given):
  --domain DOMAIN     Registrable domain, also the Cloudflare zone. Required to provision.
  --subdomain LABEL   Host label the app answers on. Empty puts it on the apex. Default: bi.
  --tfvars FILE       Extra Terraform variables, one per line, as -var-file. Optional.

  Terraform credentials come from the environment: AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY for
  Lightsail, CLOUDFLARE_API_TOKEN for the DNS record. State stays in the Terraform directory unless
  TF_STATE_BUCKET is set, in which case it goes to that bucket, with TF_STATE_KEY, TF_STATE_REGION
  and TF_STATE_ENDPOINT (for R2 or another S3-compatible store) as needed.

Destination:
  --host HOST         Hostname or IP of an existing instance. Skips provisioning.
  --ssh-key PATH      SSH private key. Generated by Terraform when omitted while provisioning.
  --ssh-user USER     SSH user on the instance. Default: ubuntu.

Hand-off to deploy/hosted/deploy.sh:
  --skip-build        Reuse the image already built locally.
  --skip-transfer     Skip sending the image; only copy the files and restart the stack.
  --no-verify         Skip the post-deploy checks.
  -h, --help          This text
EOF
}

domain=""
subdomain="bi"
tfvars=""
host=""
ssh_key=""
ssh_user="ubuntu"
forward=()

# Set by the provisioning step. Empty when --host is given, since then the addresses are already in
# the environment file.
public_url=""
hostname=""

while [ $# -gt 0 ]; do
  case "$1" in
    --domain) domain="${2:-}"; shift 2 ;;
    --subdomain) subdomain="${2:-}"; shift 2 ;;
    --tfvars) tfvars="${2:-}"; shift 2 ;;
    --host) host="${2:-}"; shift 2 ;;
    --ssh-key) ssh_key="${2:-}"; shift 2 ;;
    --ssh-user) ssh_user="${2:-}"; shift 2 ;;
    --skip-build) forward+=(--skip-build); shift ;;
    --skip-transfer) forward+=(--skip-transfer); shift ;;
    --no-verify) forward+=(--no-verify); shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
tf_dir="$repo_root/deploy/terraform/lightsail"
hosted_dir="$repo_root/deploy/hosted"
env_file="$hosted_dir/.env"
env_example="$hosted_dir/.env.example"
state_key="$tf_dir/lightsail.pem"

log() { printf '\033[1m==>\033[0m %s\n' "$*"; }
die() { printf 'error: %s\n' "$*" >&2; exit 1; }

# ─── Tools ──────────────────────────────────────────────────────────────────
# Nothing is installed here. The message says what to install and where the alternative is, because
# a launch that fails on an unstated dependency is worse than one that never starts.

missing=()
require() { command -v "$1" >/dev/null 2>&1 || missing+=("$1"); }

require docker
require ssh
require curl
if [ -z "$host" ]; then
  require terraform
fi

if [ "${#missing[@]}" -gt 0 ]; then
  printf 'error: missing tools: %s\n' "${missing[*]}" >&2
  case " ${missing[*]} " in
    *" terraform "*) printf '  terraform: https://developer.hashicorp.com/terraform/install\n' >&2 ;;
  esac
  case " ${missing[*]} " in
    *" docker "*) printf '  docker: https://docs.docker.com/get-docker/\n' >&2 ;;
  esac
  printf 'Run the "Deploy Hosted" workflow in GitHub Actions to launch the same deployment without local tools.\n' >&2
  exit 1
fi

# ─── Provision ──────────────────────────────────────────────────────────────

if [ -z "$host" ]; then
  [ -n "$domain" ] || die "--domain is required when --host is not given (or pass --host to deploy to an instance that exists)."
  [ -d "$tf_dir" ] || die "$tf_dir does not exist."

  log "Creating the instance for $domain with Terraform"

  # Terraform keeps the instance's generated private key in its state, so a run without a disk to
  # keep that state on needs it in a bucket. Set TF_STATE_BUCKET, and TF_STATE_KEY, TF_STATE_REGION
  # and TF_STATE_ENDPOINT (for R2 or another S3-compatible store) as needed. Without it, the state
  # stays in $tf_dir, which is what a local run wants.
  init_args=(-input=false)
  if [ -n "${TF_STATE_BUCKET:-}" ]; then
    state_key_path="${TF_STATE_KEY:-statsparrot/lightsail.tfstate}"
    init_args+=(-backend-config="bucket=$TF_STATE_BUCKET")
    init_args+=(-backend-config="key=$state_key_path")
    init_args+=(-backend-config="region=${TF_STATE_REGION:-eu-west-1}")
    if [ -n "${TF_STATE_ENDPOINT:-}" ]; then
      init_args+=(-backend-config="endpoint=$TF_STATE_ENDPOINT")
      init_args+=(-backend-config="skip_credentials_validation=true")
      init_args+=(-backend-config="skip_region_validation=true")
      init_args+=(-backend-config="skip_requesting_account_id=true")
      init_args+=(-backend-config="use_path_style=true")
    fi
    # Separate credentials for the state bucket, because the provider needs AWS credentials for
    # Lightsail and an S3-compatible store such as R2 has its own key pair.
    if [ -n "${TF_STATE_ACCESS_KEY:-}" ]; then
      init_args+=(-backend-config="access_key=$TF_STATE_ACCESS_KEY")
    fi
    if [ -n "${TF_STATE_SECRET_KEY:-}" ]; then
      init_args+=(-backend-config="secret_key=$TF_STATE_SECRET_KEY")
    fi
    log "Terraform state goes to s3://$TF_STATE_BUCKET/$state_key_path"
  else
    init_args+=(-backend=false)
  fi
  terraform -chdir="$tf_dir" init "${init_args[@]}"

  # Interactive when a person is watching, unattended in CI. Terraform asks about the SSH CIDR
  # either way through the variables file, not through a prompt.
  apply_args=(-input=false -var "domain=$domain" -var "subdomain=$subdomain")
  if [ -n "$tfvars" ]; then
    apply_args+=(-var-file "$tfvars")
  fi
  if [ -t 0 ]; then
    terraform -chdir="$tf_dir" apply "${apply_args[@]}"
  else
    terraform -chdir="$tf_dir" apply -auto-approve "${apply_args[@]}"
  fi

  host="$(terraform -chdir="$tf_dir" output -raw static_ip)"
  public_url="$(terraform -chdir="$tf_dir" output -raw public_url)"
  hostname="$(terraform -chdir="$tf_dir" output -raw hostname)"

  [ -n "$host" ] || die "Terraform produced no static IP."

  # Lightsail generates the key pair when the variables do not name one, and the private half
  # only exists in the state until it is written out.
  if [ -z "$ssh_key" ]; then
    if terraform -chdir="$tf_dir" output -raw private_key_pem > "$state_key.tmp" 2>/dev/null; then
      if [ -s "$state_key.tmp" ]; then
        if [ -f "$state_key" ]; then
          log "Keeping the existing $state_key"
          rm -f "$state_key.tmp"
        else
          mv "$state_key.tmp" "$state_key"
          chmod 600 "$state_key"
          log "Wrote the generated private key to $state_key"
        fi
        ssh_key="$state_key"
      else
        rm -f "$state_key.tmp"
      fi
    else
      rm -f "$state_key.tmp"
    fi
  fi
else
  log "Deploying to the existing instance $host; skipping Terraform"
fi

# ─── Fill in the two values that depend on the host ─────────────────────────

set_env_var() { # file key value
  local file="$1" key="$2" value="$3" tmp
  tmp="$(mktemp)"
  awk -v key="$key" -v value="$value" '
    index($0, key "=") == 1 { print key "=" value; found = 1; next }
    { print }
    END { if (!found) print key "=" value }
  ' "$file" > "$tmp"
  mv "$tmp" "$file"
}

if [ -n "$public_url" ] && [ -n "$hostname" ]; then
  if [ ! -f "$env_file" ]; then
    cp "$env_example" "$env_file"
    log "Created $env_file from .env.example"
  fi
  set_env_var "$env_file" STATSPARROT_SERVE_PUBLIC_URL "$public_url"
  set_env_var "$env_file" STATSPARROT_DOMAIN "$hostname"
  chmod 600 "$env_file"
  log "$env_file: STATSPARROT_SERVE_PUBLIC_URL=$public_url  STATSPARROT_DOMAIN=$hostname"
fi

[ -f "$env_file" ] || die "$env_file does not exist. Copy .env.example to .env and fill it in."

# Values that ship as placeholders in .env.example. A deployment with any of them left is a
# deployment that starts and then fails on the first request, so stop before building anything.
placeholders=()
for key in \
  STATSPARROT_ADMIN_DATABASE_URL \
  STATSPARROT_ADMIN_RIVER_DATABASE_URL \
  STATSPARROT_ADMIN_SESSION_KEY_PAIRS \
  STATSPARROT_RUNTIME_SESSION_KEY_PAIRS \
  STATSPARROT_ADMIN_AUTH_DOMAIN \
  STATSPARROT_ADMIN_AUTH_CLIENT_ID \
  STATSPARROT_ADMIN_AUTH_CLIENT_SECRET
do
  value="$(sed -n "s/^$key=//p" "$env_file" | head -1)"
  case "$value" in
    ""|*example.com*|*replace-me*|*your-tenant*)
      placeholders+=("$key") ;;
  esac
done

if [ "${#placeholders[@]}" -gt 0 ]; then
  printf 'error: %s still holds a placeholder or is empty:\n' "$env_file" >&2
  printf '  %s\n' "${placeholders[@]}" >&2
  cat >&2 <<'EOF'
Fill them in and run this command again. The commented lines in .env.example say what each one
needs: a Postgres URL (the admin server migrates it on boot), two session keys from
"openssl rand -hex 32", and the OIDC provider's domain, client id and client secret.
EOF
  exit 1
fi

# ─── Wait for the instance to finish booting ────────────────────────────────

ssh_opts=(-o BatchMode=yes -o StrictHostKeyChecking=accept-new -o ConnectTimeout=10)
if [ -n "$ssh_key" ]; then
  ssh_opts+=(-i "$ssh_key")
fi

log "Waiting for $ssh_user@$host to accept SSH and for cloud-init to finish"
attempt=0
until ssh "${ssh_opts[@]}" "$ssh_user@$host" true 2>/dev/null; do
  attempt=$((attempt + 1))
  if [ "$attempt" -ge 30 ]; then
    die "SSH did not come up on $ssh_user@$host within 5 minutes. Check the instance in the Lightsail console."
  fi
  sleep 10
done

# Docker arrives with cloud-init. Waiting here means the hand-off does not race it.
if ! ssh "${ssh_opts[@]}" "$ssh_user@$host" 'cloud-init status --wait' 2>/dev/null; then
  log "cloud-init did not report success; continuing anyway and letting the deploy checks decide"
fi

# ─── Hand over to the deploy script ─────────────────────────────────────────

deploy_args=(--host "$host" --user "$ssh_user")
if [ -n "$ssh_key" ]; then
  deploy_args+=(--ssh-key "$ssh_key")
fi
if [ "${#forward[@]}" -gt 0 ]; then
  deploy_args+=("${forward[@]}")
fi

log "Shipping the stack with deploy/hosted/deploy.sh"
exec "$hosted_dir/deploy.sh" "${deploy_args[@]}"
